[package]
name = "xorstr"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.95"
quote = "1.0.40"
rand = "0.9.1"
syn = "2.0.104"

[lib]
crate-type = ["procmacro"]
proc-macro = true
